import { Router, type IRouter } from "express";
import healthRouter from "./health";
import uptimeRouter from "./uptime";
import authRouter from "./auth";
import usersRouter from "./users";
import projectsRouter from "./projects";
import tasksRouter from "./tasks";
import toolsRouter from "./tools";
import vaultRouter from "./vault";
import vaultSecurityRouter from "./vault-security";
import leaderboardRouter from "./leaderboard";
import broadcastRouter from "./broadcast";
import settingsRouter from "./settings";
import telemetryRouter from "./telemetry";
import aiRouter from "./ai";
import emailRoutingRouter from "./email-routing";
import telegramRouter from "./telegram";
import emailAccountsRouter from "./email-accounts";
import emailComposeRouter from "./email-compose";
import supportRouter from "./support";
import referralsRouter from "./referrals";
import eventsRouter from "./events";
import syncRouter from "./sync";
import polymarketRouter from "./polymarket";
import adminWalletRouter from "./admin-wallet";
import configRouter from "./config";
import layoutRouter from "./layout";
import marketplaceUsdtRouter from "./marketplace-usdt";
import emailRouter from "./email";
import walletsRouter from "./wallets";
import logsRouter from "./logs";
import pluginsRouter from "./plugins";
import subscriptionsRouter from "./subscriptions";
import paymentsRouter from "./payments";
import creditsRouter from "./credits";
import telemetryStreamRouter from "./telemetry-stream";
import localAccountsRouter from "./local-accounts";
import kycRouter from "./kyc";
import gameEntriesRouter from "./game-entries";
import messagesRouter from "./messages";
import aiActionsRouter from "./ai-actions";
import notificationsRouter from "./notifications";
import functionsRouter from "./functions";
import historyRouter from "./history";
import earnLinksRouter from "./earn-links";
import categoriesRouter from "./categories";
import teamsRouter from "./teams";
import contentRouter from "./content";
import entitiesRouter from "./entities";
import twoFactorRouter from "./two-factor";
import bulkRouter from "./bulk";
import networksRouter from "./networks";
import rewardLinksRouter from "./reward-links";
import adTasksRouter from "./ad-tasks";
import searchRouter from "./search";
import nftSubscriptionsRouter from "./nft-subscriptions";
import ayzenMailRouter from "./ayzen-mail";
import marketplaceRouter from "./marketplace";
import marketplaceCartRouter from "./marketplace-cart";
import marketplaceReviewsRouter from "./marketplace-reviews";
import marketplaceOffersRouter from "./marketplace-offers";
import marketplaceCouponsRouter from "./marketplace-coupons";
import marketplaceReportsRouter from "./marketplace-reports";
import marketplaceAnalyticsRouter from "./marketplace-analytics";
import marketplaceBundlesRouter from "./marketplace-bundles";
import marketplaceAlertsRouter from "./marketplace-alerts";
import marketplaceDiscoveryRouter from "./marketplace-discovery";
import marketplaceAznRouter from "./marketplace-azn";
import marketplaceNftRouter from "./marketplace-nft";
import marketplaceVaultRouter from "./marketplace-vault";
import marketplaceMarketConfigRouter from "./marketplace-market-config";
import marketplaceGameRouter from "./marketplace-game";
import marketplaceWalletRouter from "./marketplace-wallet";
import marketplaceSpotRouter from "./marketplace-spot";
import aiAgentRouter from "./ai-agent";
import securityRouter from "./security";
import checkinRouter from "./checkin";
import watchlistRouter from "./watchlist";
import shellRouter from "./shell";
import devPanelRouter from "./dev-panel";
import keyManagerRouter from "./key-manager";
import devNavRouter from "./dev-nav";
import navRouter from "./nav";
import mcpAgentsRouter from "./mcp-agents";
import uiThemeRouter from "./ui-theme";
import customButtonsRouter from "./custom-buttons";
import apiKeysRouter from "./api-keys";
import valueHistoryRouter from "./value-history";
import vaultSharesRouter from "./vault-shares";
import vaultEntityLinksRouter from "./vault-entity-links";

const router: IRouter = Router();

router.use(shellRouter);
router.use(eventsRouter);
router.use(logsRouter);
router.use(healthRouter);
router.use(uptimeRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(emailRouter);
router.use(walletsRouter);
router.use(projectsRouter);
router.use(tasksRouter);
router.use(toolsRouter);
router.use(vaultRouter);
router.use(vaultSecurityRouter);
router.use(leaderboardRouter);
router.use(broadcastRouter);
router.use(settingsRouter);
router.use(pluginsRouter);
router.use(telemetryRouter);
router.use(aiRouter);
router.use(emailRoutingRouter);
router.use(telegramRouter);
router.use(emailAccountsRouter);
router.use(emailComposeRouter);
router.use(supportRouter);
router.use(referralsRouter);
router.use(subscriptionsRouter);
router.use(paymentsRouter);
router.use(creditsRouter);
router.use(telemetryStreamRouter);
router.use(localAccountsRouter);
router.use(kycRouter);
router.use(gameEntriesRouter);
router.use(messagesRouter);
router.use(aiActionsRouter);
router.use(notificationsRouter);
router.use(functionsRouter);
router.use(historyRouter);
router.use(earnLinksRouter);
router.use(categoriesRouter);
router.use(teamsRouter);
router.use(contentRouter);
router.use(entitiesRouter);
router.use(vaultSharesRouter);
router.use(vaultEntityLinksRouter);
router.use(twoFactorRouter);
router.use(bulkRouter);
router.use(networksRouter);
router.use(rewardLinksRouter);
router.use(adTasksRouter);
router.use(searchRouter);
router.use(nftSubscriptionsRouter);
router.use(ayzenMailRouter);
router.use(marketplaceDiscoveryRouter);
router.use(marketplaceRouter);
router.use(marketplaceCartRouter);
router.use(marketplaceReviewsRouter);
router.use(marketplaceOffersRouter);
router.use(marketplaceCouponsRouter);
router.use(marketplaceReportsRouter);
router.use(marketplaceAnalyticsRouter);
router.use(marketplaceBundlesRouter);
router.use(marketplaceAlertsRouter);
router.use(marketplaceAznRouter);
router.use(marketplaceNftRouter);
router.use(marketplaceVaultRouter);
router.use(marketplaceMarketConfigRouter);
router.use(marketplaceGameRouter);
router.use(marketplaceWalletRouter);
router.use(marketplaceSpotRouter);
router.use(aiAgentRouter);
router.use(mcpAgentsRouter);
router.use(securityRouter);
router.use(checkinRouter);
router.use(watchlistRouter);
router.use(devPanelRouter);
router.use(keyManagerRouter);
router.use(devNavRouter);
router.use(navRouter);
router.use(uiThemeRouter);
router.use(customButtonsRouter);
router.use(syncRouter);
router.use(polymarketRouter);
router.use(adminWalletRouter);
router.use(configRouter);
router.use(layoutRouter);
router.use(marketplaceUsdtRouter);
router.use(apiKeysRouter);
router.use(valueHistoryRouter);

export default router;
